In [2]:
import numpy as np

#criar um vetor linha
array_linha = np.array([1,2,3,5,8,78])
print(array_linha)

[ 1  2  3  5  8 78]


In [3]:
#criar vetor coluna
array_coluna = np.array([[1],[2],[3]])
print(array_coluna)

[[1]
 [2]
 [3]]


In [4]:
#criando matriz 
np_matriz = np.array([[10,12,13],[5,6,8],[59,2,4]])
print(np_matriz)

[[10 12 13]
 [ 5  6  8]
 [59  2  4]]


In [5]:
array_intervalda = np.linspace(0,50,num=5)
print(array_intervalda)

[ 0.  12.5 25.  37.5 50. ]


In [6]:
array_randnom = np.random.randint(0,11,3)
print(array_randnom)

[6 2 5]


In [7]:
#n de linhas e colunas 
print(np_matriz.shape)

(3, 3)


In [8]:
#tipo dos elementos
print(np_matriz.dtype)

int32


In [9]:
#n de elementos 
print(np_matriz.size)

9


In [10]:
#n de dimensões
print(np_matriz.ndim)

2


In [11]:
print(np.min(np_matriz))
print(np.max(np_matriz))

2
59


In [12]:
#array random 
array_random = np.arange(6)
print(array_random)

[0 1 2 3 4 5]


In [13]:
#array para matriz 
array_rashape = array_random.reshape(2,3)
print(array_rashape)

[[0 1 2]
 [3 4 5]]


In [14]:
#desvio padrão
np.std(np_matriz)

16.55145363054105

In [15]:
#percentil
np.percentile(np_matriz,10)

3.6

In [16]:
#variância
np.var(np_matriz)

273.9506172839506

Cáculos de matrizes 


In [17]:
# Soma de matrizes
matrizA = np.array([np.random.randint(0,50,3),np.random.randint(0,50,3)])
matrizB = np.array([np.random.randint(0,20,3),np.random.randint(0,20,3)])
print(np.add(matrizA,matrizB))

[[63 25 17]
 [48 58 51]]


In [18]:
#subtração de matriz
print(np.subtract(matrizA,matrizB))

[[33 -1 15]
 [20 20 35]]


In [19]:
#multiplicação de matrizes 
print(matrizA*matrizB)

[[720 156  16]
 [476 741 344]]


Calculo Diagonal da matriz 


In [20]:
#Diagonal principal 
print(matrizA.diagonal())
#acima da principal
print(matrizA.diagonal(offset=1))
#abaixo da principal
print(matrizA.diagonal(offset=-1))
#Matriz inversa 
print(np.linalg.inv(np_matriz))

[48 39]
[12 43]
[34]
[[ 0.00775194 -0.02131783  0.01744186]
 [ 0.4379845  -0.70445736 -0.01453488]
 [-0.33333333  0.66666667  0.        ]]


Adicionar elementos na matriz 

In [21]:
add_100 = lambda i:i+100

print(add_100(np_matriz))

[[110 112 113]
 [105 106 108]
 [159 102 104]]


OPERAÇÕES LÓGICAS COM ARRAYS 

In [22]:
print(np_matriz)

print(np.where(array_linha<3))

[[10 12 13]
 [ 5  6  8]
 [59  2  4]]
(array([0, 1], dtype=int64),)
